{"uuid": "9ff5e26e-e6a5-49c4-88ce-c3a50a265c2b", "children": ["9fef6152-ae3b-4c27-8611-c41ef086053e"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'tests/tests/config.json'\n", "trace": "  File \"/Users/yaroslav.petryk/Desktop/projects/powerfox-app-native-android/tests/venv/lib/python3.10/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/yaroslav.petryk/Desktop/projects/powerfox-app-native-android/tests/venv/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/yaroslav.petryk/Desktop/projects/powerfox-app-native-android/tests/venv/lib/python3.10/site-packages/_pytest/fixtures.py\", line 883, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/Users/yaroslav.petryk/Desktop/projects/powerfox-app-native-android/tests/tests/conftest.py\", line 11, in driver\n    locale = str(config_importer.config_locale())\n  File \"/Users/yaroslav.petryk/Desktop/projects/powerfox-app-native-android/tests/helpers/config_importer.py\", line 67, in config_locale\n    config = self.config()\n  File \"/Users/yaroslav.petryk/Desktop/projects/powerfox-app-native-android/tests/helpers/config_importer.py\", line 12, in config\n    with open(self.CONFIG_PATH, 'r') as config_file:\n"}, "start": 1683573560592, "stop": 1683573560592}], "start": 1683573560592, "stop": 1683573560678}