{"name": "test_login", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: './tests/tests/config.json'", "trace": "@pytest.fixture(scope=\"session\")\n    def driver():\n>       locale = str(config_importer.config_locale())\n\nconftest.py:11: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n../helpers/config_importer.py:67: in config_locale\n    config = self.config()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <tests.helpers.config_importer.ConfigImporter object at 0x1058effd0>\n\n    def config(self):\n>       with open(self.CONFIG_PATH, 'r') as config_file:\nE       FileNotFoundError: [Errno 2] No such file or directory: './tests/tests/config.json'\n\n../helpers/config_importer.py:12: FileNotFoundError"}, "start": 1683573531183, "stop": 1683573531183, "uuid": "eea4688c-ef88-4f8b-811c-ecfb7f832a1c", "historyId": "f719506019f75754dbe06f1a899197bd", "testCaseId": "450c13c546238b16c8c855f2c4cf851f", "fullName": "tests.tests.test_budget#test_login", "labels": [{"name": "parentSuite", "value": "tests.tests"}, {"name": "suite", "value": "test_budget"}, {"name": "host", "value": "ypetryk-MacBook-Pro.local"}, {"name": "thread", "value": "2916-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.tests.test_budget"}]}